sudo: required

language: cpp
compiler:
    - gcc
    - clang

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-6
            - lcov
            - libgtest-dev
            - cmake
            - cmake-data

script: 
    - mkdir build
    - cd build
    - cmake .. 
    - make 
    - ./vector/vector
    - ./string/string

branch_pattern: master
